### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by rushi12565** [mishamyte/Nestor#8]
how should i run the nestor
i get this error when i try to run it

PS E:\Nestor-master\src\Nestor.Service> dotnet run
Unhandled exception. System.ArgumentException: Format of the initialization string does not conform to specification sta
rting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuild
er buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean bui
ldChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)

   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Nestor.Service.HostExtensions.Migrate(IHost host) in E:\Nestor-master\src\Nestor.Service\HostExtensions.cs:line 14

   at Nestor.Service.Program.Main(String[] args) in E:\Nestor-master\src\Nestor.Service\Program.cs:line 11

**Comment by mishamyte** [comment]
Hi, @rushi12565!

When u start the app with a simple `dotnet run` it starts in Production mode.

So, please, share here your `appsettings.Production.json` (sensitive data, such a db host/user/pass, part of TG of Google keys should be masked)

**Comment by rushi12565** [comment]
@mishamyte Hi, if searched all the folders but I couldn't find appsettings.Production.json
If u meant appsettings.json this is the details of the file

{ "Bot": { "ApiKey": "1462669227:xxxxxxc", "ChatId": 1278928719 }, "ConnectionStrings": { "Nestor": "ConnectionString" }, "Global": { "GoogleMapsKey": "xxxxxxxxxx", "IconsUrlFormat": "https://www.pokencyclopedia.info/sprites/3ds/ani_6/3ani__{0}__xy.gif", "IgnoredNests": [], "IgnoredPokemons": [] }, "Parser": { "PollingFrequency": 20, "CenterLat": 50.45396287500938, "CenterLng": 30.634327370665233, "Lat1": 50.56893143275417, "Lng1": 30.30712530657223, "Lat2": 50.33871424071279, "Lng2": 30.961529434727282, "Zoom": 10 }, "Serilog": { "Using": [ "Serilog.Sinks.Console" ], "MinimumLevel": { "Default": "Debug", "Override": { "Microsoft": "Warning", "System": "Warning" } }, "Enrich": [ "WithThreadId" ], "WriteTo": [ { "Name": "Console", "Args": { "outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] [{SourceContext}] {Message}{NewLine}{Exception}" } } ] }}

**Comment by rushi12565** [comment]
the syntax kinda went wrong while pasring tho lol

**Comment by mishamyte** [comment]
Yes, the `.Production` file should be created for overrides, if needed.

But it is not the reason of your problem. How familiar are you with .NET Core?

You have to install PostgreSQL (it's a database) and replace

```json
"ConnectionStrings": {
    "Nestor": "ConnectionString"
},```

with your actual connection string. Something like that:

```json
"ConnectionStrings": {
    "Nestor": "Server=localhost;Database=nestor;User Id=postgres;Password=p@ssw0rd;"
},```

_But u should have a strong password, btw_

**Comment by rushi12565** [comment]
oh OK thanks so much. I'll try and inform u
And yea I did install postgresql
u can consider me a noob if it comes to .net
